### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by jmalloc** [recoilphp/dev#20]
- [x] Blocked by https://github.com/eloquent/phony/issues/250
- [x] Blocked by https://github.com/recoilphp/api/issues/11
- [ ] Remove peridot plugin (?)
- [ ] Convert tests to use PHPUnit

**Comment by langabi** [comment]
One observation is that the version of nikic/PHP-Parser probably needs to "^4" in the composer.json, for PHP8 and even PHP >7.2 - so almost certainly worth doing in the php8 branch, but maybe also master branch.

**Comment by jmalloc** [comment]
Peridot's code coverage reporters are also using outdated deps, and will probably need to be forked in addition to `peridot` and `leo`.

PHP 8.0 issue is at https://github.com/recoilphp/dev/runs/3649712374#step:5:123
```
phpdbg -c test/etc/php.ini -qrr vendor/bin/peridot --reporter clover-code-coverage --code-coverage-path=artifacts/tests/coverage/clover.xml
[Uncaught Error in /home/runner/work/dev/dev/vendor/phpunit/php-token-stream/src/Token/Stream.php on line 189]
Error: Class "PHP_Token_NAME_QUALIFIED" not found in /home/runner/work/dev/dev/vendor/phpunit/php-token-stream/src/Token/Stream.php:189
Stack trace:
#0 /home/runner/work/dev/dev/vendor/phpunit/php-token-stream/src/Token/Stream.php(118): PHP_Token_Stream->scan('<?php\n\ndeclare(...')
```

---

```
❯ composer why phpunit/php-token-stream
phpunit/php-code-coverage  3.3.3  requires  phpunit/php-token-stream (^1.4.2)  

❯ composer why phpunit/php-code-coverage
peridot-php/peridot-code-coverage-reporters  2.0.2  requires  phpunit/php-code-coverage (^2|^3)  
```
